import type Database from "better-sqlite3";
import type { Shoe } from "../types/shoe";

type SeedShoe = Omit<Shoe, "id">;

const seedShoes: SeedShoe[] = [
  {
    name: "Nike GT Cut 3",
    brand: "Nike",
    era: "modern",
    releaseYear: 2024,
    priceKRW: 229000,
    positionTag: "guard",
    traction: 8.8,
    cushioning: 8.5,
    support: 7.4,
    stability: 7.3,
    weightScore: 8.7,
    breathability: 8.0,
    outdoorDurability: 6.2,
    retroStyleScore: 3.2,
    footWidthFit: "narrow",
    summary: "Explosive modern guard model with aggressive forefoot response.",
    imageUrl: ""
  },
  {
    name: "Nike Sabrina 2",
    brand: "Nike",
    era: "modern",
    releaseYear: 2024,
    priceKRW: 179000,
    positionTag: "guard",
    traction: 9.0,
    cushioning: 7.9,
    support: 7.6,
    stability: 8.0,
    weightScore: 8.6,
    breathability: 8.2,
    outdoorDurability: 6.5,
    retroStyleScore: 4.0,
    footWidthFit: "narrow",
    summary: "Fast guard profile with elite grip and light transition.",
    imageUrl: ""
  },
  {
    name: "adidas AE 1",
    brand: "adidas",
    era: "modern",
    releaseYear: 2024,
    priceKRW: 169000,
    positionTag: "forward",
    traction: 8.1,
    cushioning: 8.3,
    support: 8.4,
    stability: 8.7,
    weightScore: 6.9,
    breathability: 7.0,
    outdoorDurability: 8.1,
    retroStyleScore: 5.4,
    footWidthFit: "regular",
    summary: "Power-friendly modern shoe with strong frame and court bite.",
    imageUrl: ""
  },
  {
    name: "Nike KD 17",
    brand: "Nike",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 239000,
    positionTag: "forward",
    traction: 8.4,
    cushioning: 8.9,
    support: 7.5,
    stability: 7.7,
    weightScore: 7.5,
    breathability: 7.8,
    outdoorDurability: 6.7,
    retroStyleScore: 3.8,
    footWidthFit: "regular",
    summary: "Smooth cushion and long-stride comfort for versatile wings.",
    imageUrl: ""
  },
  {
    name: "New Balance TWO WXY v5",
    brand: "New Balance",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 189000,
    positionTag: "all",
    traction: 8.5,
    cushioning: 8.0,
    support: 8.2,
    stability: 8.1,
    weightScore: 7.9,
    breathability: 7.6,
    outdoorDurability: 7.8,
    retroStyleScore: 4.4,
    footWidthFit: "wide",
    summary: "Balanced modern performer with stable platform and roomy fit.",
    imageUrl: ""
  },
  {
    name: "Anta Kai 1",
    brand: "Anta",
    era: "modern",
    releaseYear: 2024,
    priceKRW: 159000,
    positionTag: "guard",
    traction: 8.7,
    cushioning: 8.1,
    support: 7.7,
    stability: 7.8,
    weightScore: 8.0,
    breathability: 7.2,
    outdoorDurability: 7.0,
    retroStyleScore: 5.1,
    footWidthFit: "regular",
    summary: "Quick-attack guard model with responsive transition feel.",
    imageUrl: ""
  },
  {
    name: "Li-Ning Gamma 1",
    brand: "Li-Ning",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 199000,
    positionTag: "forward",
    traction: 8.0,
    cushioning: 8.6,
    support: 8.0,
    stability: 8.1,
    weightScore: 7.4,
    breathability: 7.1,
    outdoorDurability: 8.3,
    retroStyleScore: 4.3,
    footWidthFit: "regular",
    summary: "Energy-return setup with better outdoor tolerance.",
    imageUrl: ""
  },
  {
    name: "Puma All Pro Nitro",
    brand: "Puma",
    era: "modern",
    releaseYear: 2024,
    priceKRW: 179000,
    positionTag: "all",
    traction: 8.3,
    cushioning: 8.2,
    support: 7.8,
    stability: 7.9,
    weightScore: 8.1,
    breathability: 8.4,
    outdoorDurability: 7.1,
    retroStyleScore: 4.8,
    footWidthFit: "regular",
    summary: "Breathable lightweight modern package for two-way play.",
    imageUrl: ""
  },
  {
    name: "Asics Unpre Ars 2",
    brand: "Asics",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 189000,
    positionTag: "guard",
    traction: 8.9,
    cushioning: 7.8,
    support: 7.8,
    stability: 8.0,
    weightScore: 8.2,
    breathability: 7.4,
    outdoorDurability: 7.6,
    retroStyleScore: 4.1,
    footWidthFit: "regular",
    summary: "Guard-focused grip machine with stable edge transitions.",
    imageUrl: ""
  },
  {
    name: "Under Armour Curry 12",
    brand: "Under Armour",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 199000,
    positionTag: "guard",
    traction: 9.1,
    cushioning: 7.9,
    support: 7.4,
    stability: 7.6,
    weightScore: 8.5,
    breathability: 8.1,
    outdoorDurability: 5.9,
    retroStyleScore: 3.7,
    footWidthFit: "narrow",
    summary: "Elite on-court bite for indoor quick-release guards.",
    imageUrl: ""
  },
  {
    name: "361 Big3 5.0 Pro",
    brand: "361",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 169000,
    positionTag: "forward",
    traction: 8.0,
    cushioning: 8.4,
    support: 8.1,
    stability: 8.2,
    weightScore: 7.2,
    breathability: 7.0,
    outdoorDurability: 8.4,
    retroStyleScore: 4.0,
    footWidthFit: "wide",
    summary: "Durable all-court setup for players splitting indoor and outdoor.",
    imageUrl: ""
  },
  {
    name: "Nike Kobe 6 Protro",
    brand: "Nike",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 239000,
    positionTag: "guard",
    traction: 9.2,
    cushioning: 8.2,
    support: 8.0,
    stability: 8.1,
    weightScore: 8.9,
    breathability: 8.3,
    outdoorDurability: 6.3,
    retroStyleScore: 6.4,
    footWidthFit: "narrow",
    summary: "Modernized classic performer with elite low-top responsiveness.",
    imageUrl: ""
  },
  {
    name: "Nike LeBron 22",
    brand: "Nike",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 249000,
    positionTag: "forward",
    traction: 8.1,
    cushioning: 9.3,
    support: 8.7,
    stability: 8.5,
    weightScore: 6.4,
    breathability: 6.8,
    outdoorDurability: 7.2,
    retroStyleScore: 4.6,
    footWidthFit: "wide",
    summary: "Max-cushion power setup with strong containment.",
    imageUrl: ""
  },
  {
    name: "Nike Ja 2",
    brand: "Nike",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 159000,
    positionTag: "guard",
    traction: 8.9,
    cushioning: 7.6,
    support: 7.4,
    stability: 7.5,
    weightScore: 8.6,
    breathability: 8.0,
    outdoorDurability: 6.4,
    retroStyleScore: 4.1,
    footWidthFit: "regular",
    summary: "Aggressive first-step feel for speed guards.",
    imageUrl: ""
  },
  {
    name: "Nike Zoom Freak 6",
    brand: "Nike",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 179000,
    positionTag: "forward",
    traction: 8.2,
    cushioning: 8.4,
    support: 8.0,
    stability: 8.1,
    weightScore: 7.3,
    breathability: 7.4,
    outdoorDurability: 7.7,
    retroStyleScore: 4.2,
    footWidthFit: "regular",
    summary: "Dynamic power wing profile with stable landings.",
    imageUrl: ""
  },
  {
    name: "Nike Book 1",
    brand: "Nike",
    era: "modern",
    releaseYear: 2024,
    priceKRW: 169000,
    positionTag: "guard",
    traction: 8.5,
    cushioning: 7.5,
    support: 7.8,
    stability: 8.0,
    weightScore: 7.8,
    breathability: 7.3,
    outdoorDurability: 7.0,
    retroStyleScore: 6.6,
    footWidthFit: "regular",
    summary: "Low-profile shot-creator model with classic cues.",
    imageUrl: ""
  },
  {
    name: "Nike GT Hustle 3",
    brand: "Nike",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 219000,
    positionTag: "all",
    traction: 8.1,
    cushioning: 9.0,
    support: 7.9,
    stability: 7.8,
    weightScore: 7.0,
    breathability: 7.2,
    outdoorDurability: 6.9,
    retroStyleScore: 3.9,
    footWidthFit: "regular",
    summary: "Bouncy cushioning built for repeat takeoff comfort.",
    imageUrl: ""
  },
  {
    name: "adidas Harden Vol 8",
    brand: "adidas",
    era: "modern",
    releaseYear: 2024,
    priceKRW: 189000,
    positionTag: "guard",
    traction: 8.7,
    cushioning: 8.5,
    support: 8.2,
    stability: 8.3,
    weightScore: 7.1,
    breathability: 7.0,
    outdoorDurability: 7.4,
    retroStyleScore: 5.0,
    footWidthFit: "wide",
    summary: "Step-back friendly grip and supportive shell.",
    imageUrl: ""
  },
  {
    name: "adidas Dame 9",
    brand: "adidas",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 169000,
    positionTag: "guard",
    traction: 8.6,
    cushioning: 8.0,
    support: 7.9,
    stability: 8.0,
    weightScore: 7.7,
    breathability: 7.4,
    outdoorDurability: 8.0,
    retroStyleScore: 4.9,
    footWidthFit: "regular",
    summary: "All-court guard package with dependable outdoor life.",
    imageUrl: ""
  },
  {
    name: "adidas D.O.N. Issue 6",
    brand: "adidas",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 159000,
    positionTag: "guard",
    traction: 8.4,
    cushioning: 7.8,
    support: 7.6,
    stability: 7.9,
    weightScore: 8.0,
    breathability: 7.9,
    outdoorDurability: 7.2,
    retroStyleScore: 4.5,
    footWidthFit: "regular",
    summary: "Quick-release perimeter shoe with balanced setup.",
    imageUrl: ""
  },
  {
    name: "Jordan Luka 3",
    brand: "Jordan",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 179000,
    positionTag: "guard",
    traction: 8.5,
    cushioning: 8.1,
    support: 8.0,
    stability: 8.2,
    weightScore: 7.4,
    breathability: 7.1,
    outdoorDurability: 7.4,
    retroStyleScore: 5.3,
    footWidthFit: "regular",
    summary: "Stable stop-and-go platform for craft-heavy guards.",
    imageUrl: ""
  },
  {
    name: "Jordan Tatum 3",
    brand: "Jordan",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 169000,
    positionTag: "forward",
    traction: 8.2,
    cushioning: 8.0,
    support: 7.8,
    stability: 7.9,
    weightScore: 8.0,
    breathability: 7.8,
    outdoorDurability: 6.9,
    retroStyleScore: 5.0,
    footWidthFit: "regular",
    summary: "Light wing model with balanced responsiveness.",
    imageUrl: ""
  },
  {
    name: "Jordan Zion 3",
    brand: "Jordan",
    era: "modern",
    releaseYear: 2024,
    priceKRW: 179000,
    positionTag: "forward",
    traction: 8.0,
    cushioning: 8.7,
    support: 8.5,
    stability: 8.4,
    weightScore: 6.8,
    breathability: 6.7,
    outdoorDurability: 7.6,
    retroStyleScore: 4.7,
    footWidthFit: "wide",
    summary: "Power-oriented setup with high-impact support.",
    imageUrl: ""
  },
  {
    name: "Under Armour Spawn 6",
    brand: "Under Armour",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 149000,
    positionTag: "all",
    traction: 8.3,
    cushioning: 7.7,
    support: 8.0,
    stability: 8.1,
    weightScore: 7.8,
    breathability: 7.6,
    outdoorDurability: 8.1,
    retroStyleScore: 4.2,
    footWidthFit: "wide",
    summary: "Budget-friendly performer with durable outsole.",
    imageUrl: ""
  },
  {
    name: "Under Armour Lockdown 7",
    brand: "Under Armour",
    era: "modern",
    releaseYear: 2024,
    priceKRW: 109000,
    positionTag: "all",
    traction: 7.8,
    cushioning: 7.1,
    support: 7.9,
    stability: 8.0,
    weightScore: 7.2,
    breathability: 7.1,
    outdoorDurability: 8.4,
    retroStyleScore: 3.8,
    footWidthFit: "wide",
    summary: "Entry-level all-court model for frequent outdoor runs.",
    imageUrl: ""
  },
  {
    name: "Puma MB.04",
    brand: "Puma",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 179000,
    positionTag: "guard",
    traction: 8.4,
    cushioning: 8.4,
    support: 7.7,
    stability: 7.8,
    weightScore: 7.6,
    breathability: 7.5,
    outdoorDurability: 7.2,
    retroStyleScore: 5.5,
    footWidthFit: "regular",
    summary: "Flair-heavy guard sneaker with responsive foam ride.",
    imageUrl: ""
  },
  {
    name: "Puma Stewie 3",
    brand: "Puma",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 169000,
    positionTag: "forward",
    traction: 8.3,
    cushioning: 8.1,
    support: 8.0,
    stability: 8.2,
    weightScore: 7.7,
    breathability: 7.7,
    outdoorDurability: 7.5,
    retroStyleScore: 4.8,
    footWidthFit: "regular",
    summary: "Balanced wing setup with stable sidewall containment.",
    imageUrl: ""
  },
  {
    name: "Anta Shock Wave 6",
    brand: "Anta",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 169000,
    positionTag: "guard",
    traction: 8.8,
    cushioning: 8.0,
    support: 8.1,
    stability: 8.1,
    weightScore: 8.2,
    breathability: 7.5,
    outdoorDurability: 7.9,
    retroStyleScore: 4.4,
    footWidthFit: "regular",
    summary: "Fast attack profile with reliable edge grip.",
    imageUrl: ""
  },
  {
    name: "Anta KT 10",
    brand: "Anta",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 179000,
    positionTag: "guard",
    traction: 8.5,
    cushioning: 8.3,
    support: 8.2,
    stability: 8.1,
    weightScore: 7.5,
    breathability: 7.3,
    outdoorDurability: 8.2,
    retroStyleScore: 4.6,
    footWidthFit: "regular",
    summary: "Shooter-oriented stable base with strong durability.",
    imageUrl: ""
  },
  {
    name: "Li-Ning Way of Wade 11",
    brand: "Li-Ning",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 239000,
    positionTag: "guard",
    traction: 8.7,
    cushioning: 8.8,
    support: 8.3,
    stability: 8.4,
    weightScore: 7.3,
    breathability: 7.0,
    outdoorDurability: 7.8,
    retroStyleScore: 5.4,
    footWidthFit: "regular",
    summary: "Premium responsive build with secure lateral control.",
    imageUrl: ""
  },
  {
    name: "Li-Ning Yushuai 18",
    brand: "Li-Ning",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 189000,
    positionTag: "forward",
    traction: 8.4,
    cushioning: 8.4,
    support: 8.2,
    stability: 8.3,
    weightScore: 7.4,
    breathability: 7.1,
    outdoorDurability: 8.2,
    retroStyleScore: 4.2,
    footWidthFit: "wide",
    summary: "Stable high-mileage setup for all-court sessions.",
    imageUrl: ""
  },
  {
    name: "Asics Gelburst 28",
    brand: "Asics",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 199000,
    positionTag: "guard",
    traction: 8.8,
    cushioning: 7.8,
    support: 8.1,
    stability: 8.2,
    weightScore: 8.1,
    breathability: 7.3,
    outdoorDurability: 7.5,
    retroStyleScore: 4.1,
    footWidthFit: "narrow",
    summary: "Japanese court-style grip monster with clean transitions.",
    imageUrl: ""
  },
  {
    name: "New Balance Hesi Low v3",
    brand: "New Balance",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 169000,
    positionTag: "guard",
    traction: 8.6,
    cushioning: 7.7,
    support: 7.8,
    stability: 7.9,
    weightScore: 8.3,
    breathability: 8.2,
    outdoorDurability: 7.1,
    retroStyleScore: 4.0,
    footWidthFit: "regular",
    summary: "Low-cut shifty guard option with light feel.",
    imageUrl: ""
  },
  {
    name: "Peak TAICHI Flash 5",
    brand: "Peak",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 159000,
    positionTag: "forward",
    traction: 8.0,
    cushioning: 8.5,
    support: 8.0,
    stability: 8.1,
    weightScore: 7.2,
    breathability: 7.0,
    outdoorDurability: 8.3,
    retroStyleScore: 4.1,
    footWidthFit: "wide",
    summary: "Comfort-first all-court build with strong outsole life.",
    imageUrl: ""
  },
  {
    name: "361 AG5 Pro",
    brand: "361",
    era: "modern",
    releaseYear: 2025,
    priceKRW: 179000,
    positionTag: "guard",
    traction: 8.5,
    cushioning: 8.2,
    support: 8.0,
    stability: 8.1,
    weightScore: 7.9,
    breathability: 7.4,
    outdoorDurability: 8.0,
    retroStyleScore: 4.2,
    footWidthFit: "regular",
    summary: "Guard control shoe with durable traction package.",
    imageUrl: ""
  },
  {
    name: "Rigorer AR1",
    brand: "Rigorer",
    era: "modern",
    releaseYear: 2024,
    priceKRW: 149000,
    positionTag: "guard",
    traction: 8.4,
    cushioning: 7.8,
    support: 7.7,
    stability: 7.8,
    weightScore: 8.2,
    breathability: 7.9,
    outdoorDurability: 7.5,
    retroStyleScore: 4.7,
    footWidthFit: "regular",
    summary: "Value guard shoe with quick break-in and agility.",
    imageUrl: ""
  },

  {
    name: "Air Jordan 1 Retro High",
    brand: "Jordan",
    era: "retro",
    releaseYear: 1985,
    priceKRW: 209000,
    positionTag: "all",
    traction: 6.9,
    cushioning: 5.8,
    support: 6.7,
    stability: 6.8,
    weightScore: 5.5,
    breathability: 5.6,
    outdoorDurability: 7.2,
    retroStyleScore: 9.8,
    footWidthFit: "regular",
    summary: "Iconic retro silhouette, style-forward and lifestyle-friendly.",
    imageUrl: ""
  },
  {
    name: "Nike Air Force 1",
    brand: "Nike",
    era: "retro",
    releaseYear: 1982,
    priceKRW: 149000,
    positionTag: "all",
    traction: 6.1,
    cushioning: 6.2,
    support: 7.1,
    stability: 7.2,
    weightScore: 4.8,
    breathability: 5.4,
    outdoorDurability: 7.9,
    retroStyleScore: 9.4,
    footWidthFit: "wide",
    summary: "Heavy classic with durable cupsole and heritage appeal.",
    imageUrl: ""
  },
  {
    name: "Converse Chuck Taylor All Star",
    brand: "Converse",
    era: "retro",
    releaseYear: 1917,
    priceKRW: 85000,
    positionTag: "all",
    traction: 5.3,
    cushioning: 4.2,
    support: 4.8,
    stability: 5.7,
    weightScore: 6.8,
    breathability: 6.1,
    outdoorDurability: 6.0,
    retroStyleScore: 9.2,
    footWidthFit: "narrow",
    summary: "Pure classic feel with minimal cushion and timeless profile.",
    imageUrl: ""
  },
  {
    name: "Reebok Question Mid",
    brand: "Reebok",
    era: "retro",
    releaseYear: 1996,
    priceKRW: 179000,
    positionTag: "guard",
    traction: 6.6,
    cushioning: 6.4,
    support: 6.9,
    stability: 7.0,
    weightScore: 5.2,
    breathability: 5.9,
    outdoorDurability: 7.0,
    retroStyleScore: 9.1,
    footWidthFit: "regular",
    summary: "90s icon with stable shell and classic court identity.",
    imageUrl: ""
  },
  {
    name: "adidas Forum 84",
    brand: "adidas",
    era: "retro",
    releaseYear: 1984,
    priceKRW: 159000,
    positionTag: "all",
    traction: 6.0,
    cushioning: 5.7,
    support: 6.8,
    stability: 6.9,
    weightScore: 5.1,
    breathability: 5.5,
    outdoorDurability: 7.1,
    retroStyleScore: 8.9,
    footWidthFit: "regular",
    summary: "Vintage ankle-support profile for style and stable rides.",
    imageUrl: ""
  },
  {
    name: "Nike Zoom Generation Retro",
    brand: "Nike",
    era: "retro",
    releaseYear: 2003,
    priceKRW: 219000,
    positionTag: "forward",
    traction: 6.7,
    cushioning: 6.8,
    support: 7.3,
    stability: 7.4,
    weightScore: 5.4,
    breathability: 5.7,
    outdoorDurability: 7.3,
    retroStyleScore: 8.8,
    footWidthFit: "regular",
    summary: "Early-2000s power wing shape with robust sidewall feel.",
    imageUrl: ""
  },
  {
    name: "New Balance 550",
    brand: "New Balance",
    era: "retro",
    releaseYear: 1989,
    priceKRW: 149000,
    positionTag: "all",
    traction: 6.2,
    cushioning: 5.9,
    support: 6.5,
    stability: 6.8,
    weightScore: 5.7,
    breathability: 6.0,
    outdoorDurability: 7.2,
    retroStyleScore: 8.6,
    footWidthFit: "wide",
    summary: "Casual-friendly retro court model with broad fit comfort.",
    imageUrl: ""
  },
  {
    name: "Puma Clyde Hardwood Retro",
    brand: "Puma",
    era: "retro",
    releaseYear: 1973,
    priceKRW: 129000,
    positionTag: "all",
    traction: 6.0,
    cushioning: 5.6,
    support: 6.2,
    stability: 6.3,
    weightScore: 6.1,
    breathability: 6.2,
    outdoorDurability: 6.8,
    retroStyleScore: 8.7,
    footWidthFit: "regular",
    summary: "Low-cut classic with vintage court DNA and casual crossover.",
    imageUrl: ""
  },
  {
    name: "Air Jordan 3 Retro",
    brand: "Jordan",
    era: "retro",
    releaseYear: 1988,
    priceKRW: 239000,
    positionTag: "all",
    traction: 6.4,
    cushioning: 6.5,
    support: 7.0,
    stability: 7.1,
    weightScore: 5.3,
    breathability: 5.9,
    outdoorDurability: 7.2,
    retroStyleScore: 9.6,
    footWidthFit: "regular",
    summary: "Heritage icon with strong lifestyle crossover appeal.",
    imageUrl: ""
  },
  {
    name: "Air Jordan 4 Retro",
    brand: "Jordan",
    era: "retro",
    releaseYear: 1989,
    priceKRW: 259000,
    positionTag: "all",
    traction: 6.3,
    cushioning: 6.4,
    support: 7.1,
    stability: 7.2,
    weightScore: 5.1,
    breathability: 5.5,
    outdoorDurability: 7.1,
    retroStyleScore: 9.7,
    footWidthFit: "regular",
    summary: "Classic high-top profile with premium retro identity.",
    imageUrl: ""
  },
  {
    name: "Air Jordan 11 Retro",
    brand: "Jordan",
    era: "retro",
    releaseYear: 1995,
    priceKRW: 279000,
    positionTag: "all",
    traction: 6.8,
    cushioning: 6.6,
    support: 7.2,
    stability: 7.3,
    weightScore: 5.0,
    breathability: 5.4,
    outdoorDurability: 6.9,
    retroStyleScore: 9.8,
    footWidthFit: "regular",
    summary: "Patent leather legend with all-time iconic style.",
    imageUrl: ""
  },
  {
    name: "Nike Air More Uptempo",
    brand: "Nike",
    era: "retro",
    releaseYear: 1996,
    priceKRW: 219000,
    positionTag: "forward",
    traction: 6.2,
    cushioning: 6.8,
    support: 7.4,
    stability: 7.5,
    weightScore: 4.6,
    breathability: 5.2,
    outdoorDurability: 7.4,
    retroStyleScore: 9.3,
    footWidthFit: "wide",
    summary: "Bold 90s aesthetic with robust full-length Air feel.",
    imageUrl: ""
  },
  {
    name: "Nike Zoom Flight 95",
    brand: "Nike",
    era: "retro",
    releaseYear: 1995,
    priceKRW: 199000,
    positionTag: "guard",
    traction: 6.4,
    cushioning: 6.3,
    support: 6.9,
    stability: 7.0,
    weightScore: 5.6,
    breathability: 5.7,
    outdoorDurability: 6.8,
    retroStyleScore: 8.9,
    footWidthFit: "regular",
    summary: "Distinctive bug-eye design with nostalgic court feel.",
    imageUrl: ""
  },
  {
    name: "Nike Air Penny 2",
    brand: "Nike",
    era: "retro",
    releaseYear: 1996,
    priceKRW: 219000,
    positionTag: "forward",
    traction: 6.5,
    cushioning: 6.9,
    support: 7.2,
    stability: 7.3,
    weightScore: 5.0,
    breathability: 5.4,
    outdoorDurability: 7.0,
    retroStyleScore: 9.0,
    footWidthFit: "regular",
    summary: "Bulky retro runner with signature Penny-era style.",
    imageUrl: ""
  },
  {
    name: "Nike Air Foamposite One",
    brand: "Nike",
    era: "retro",
    releaseYear: 1997,
    priceKRW: 289000,
    positionTag: "center",
    traction: 6.1,
    cushioning: 7.0,
    support: 7.8,
    stability: 7.9,
    weightScore: 4.4,
    breathability: 4.6,
    outdoorDurability: 7.5,
    retroStyleScore: 9.2,
    footWidthFit: "narrow",
    summary: "Molded shell classic with premium throwback silhouette.",
    imageUrl: ""
  },
  {
    name: "Converse Weapon",
    brand: "Converse",
    era: "retro",
    releaseYear: 1986,
    priceKRW: 149000,
    positionTag: "all",
    traction: 5.9,
    cushioning: 5.6,
    support: 6.8,
    stability: 6.9,
    weightScore: 5.3,
    breathability: 5.8,
    outdoorDurability: 6.9,
    retroStyleScore: 8.8,
    footWidthFit: "regular",
    summary: "Vintage high-top with legendary hardwood heritage.",
    imageUrl: ""
  },
  {
    name: "Converse Pro Leather",
    brand: "Converse",
    era: "retro",
    releaseYear: 1976,
    priceKRW: 129000,
    positionTag: "all",
    traction: 5.8,
    cushioning: 5.2,
    support: 6.2,
    stability: 6.4,
    weightScore: 5.8,
    breathability: 6.0,
    outdoorDurability: 6.6,
    retroStyleScore: 8.5,
    footWidthFit: "regular",
    summary: "Simple retro leather build for daily classic style.",
    imageUrl: ""
  },
  {
    name: "Reebok Shaqnosis",
    brand: "Reebok",
    era: "retro",
    releaseYear: 1995,
    priceKRW: 209000,
    positionTag: "center",
    traction: 6.0,
    cushioning: 6.6,
    support: 7.5,
    stability: 7.6,
    weightScore: 4.7,
    breathability: 5.1,
    outdoorDurability: 7.3,
    retroStyleScore: 9.1,
    footWidthFit: "wide",
    summary: "Heavy-duty 90s center silhouette with bold patterning.",
    imageUrl: ""
  },
  {
    name: "Reebok Pump Omni Zone II",
    brand: "Reebok",
    era: "retro",
    releaseYear: 1991,
    priceKRW: 219000,
    positionTag: "guard",
    traction: 6.2,
    cushioning: 6.3,
    support: 7.1,
    stability: 7.2,
    weightScore: 5.0,
    breathability: 5.3,
    outdoorDurability: 6.9,
    retroStyleScore: 9.0,
    footWidthFit: "regular",
    summary: "Pump-era legend with nostalgic support feel.",
    imageUrl: ""
  },
  {
    name: "adidas Rivalry 86",
    brand: "adidas",
    era: "retro",
    releaseYear: 1986,
    priceKRW: 139000,
    positionTag: "all",
    traction: 5.9,
    cushioning: 5.5,
    support: 6.6,
    stability: 6.7,
    weightScore: 5.6,
    breathability: 5.9,
    outdoorDurability: 6.8,
    retroStyleScore: 8.7,
    footWidthFit: "regular",
    summary: "Classic court heritage pair with clean retro lines.",
    imageUrl: ""
  },
  {
    name: "adidas Superstar",
    brand: "adidas",
    era: "retro",
    releaseYear: 1969,
    priceKRW: 129000,
    positionTag: "all",
    traction: 5.6,
    cushioning: 5.0,
    support: 6.1,
    stability: 6.2,
    weightScore: 6.0,
    breathability: 5.8,
    outdoorDurability: 6.9,
    retroStyleScore: 9.0,
    footWidthFit: "regular",
    summary: "Shell-toe classic recognized across generations.",
    imageUrl: ""
  },
  {
    name: "New Balance 650",
    brand: "New Balance",
    era: "retro",
    releaseYear: 1989,
    priceKRW: 159000,
    positionTag: "all",
    traction: 6.1,
    cushioning: 5.8,
    support: 6.7,
    stability: 6.8,
    weightScore: 5.5,
    breathability: 5.9,
    outdoorDurability: 7.0,
    retroStyleScore: 8.6,
    footWidthFit: "wide",
    summary: "High-cut retro companion to the 550 line.",
    imageUrl: ""
  },
  {
    name: "Ewing 33 Hi",
    brand: "Ewing Athletics",
    era: "retro",
    releaseYear: 1990,
    priceKRW: 199000,
    positionTag: "center",
    traction: 6.0,
    cushioning: 6.2,
    support: 7.4,
    stability: 7.5,
    weightScore: 4.9,
    breathability: 5.0,
    outdoorDurability: 7.1,
    retroStyleScore: 8.9,
    footWidthFit: "wide",
    summary: "True 90s big-man style with rugged upper structure.",
    imageUrl: ""
  },
  {
    name: "FILA Grant Hill 2",
    brand: "FILA",
    era: "retro",
    releaseYear: 1996,
    priceKRW: 169000,
    positionTag: "forward",
    traction: 6.1,
    cushioning: 6.1,
    support: 7.0,
    stability: 7.1,
    weightScore: 5.1,
    breathability: 5.4,
    outdoorDurability: 7.0,
    retroStyleScore: 8.8,
    footWidthFit: "regular",
    summary: "Classic 90s wing silhouette with durable tooling.",
    imageUrl: ""
  },
  {
    name: "ASICS Gel Spotlyte",
    brand: "Asics",
    era: "retro",
    releaseYear: 1987,
    priceKRW: 149000,
    positionTag: "all",
    traction: 5.8,
    cushioning: 5.9,
    support: 6.6,
    stability: 6.7,
    weightScore: 5.7,
    breathability: 6.0,
    outdoorDurability: 6.8,
    retroStyleScore: 8.5,
    footWidthFit: "regular",
    summary: "Vintage Asics hoops DNA with old-school charm.",
    imageUrl: ""
  },
  {
    name: "Nike Blazer Mid 77",
    brand: "Nike",
    era: "retro",
    releaseYear: 1977,
    priceKRW: 119000,
    positionTag: "all",
    traction: 5.5,
    cushioning: 4.9,
    support: 6.2,
    stability: 6.3,
    weightScore: 6.0,
    breathability: 5.7,
    outdoorDurability: 6.5,
    retroStyleScore: 8.9,
    footWidthFit: "regular",
    summary: "Slim classic profile for heritage court looks.",
    imageUrl: ""
  },
  {
    name: "Reebok BB 4000 II",
    brand: "Reebok",
    era: "retro",
    releaseYear: 1989,
    priceKRW: 129000,
    positionTag: "all",
    traction: 5.9,
    cushioning: 5.5,
    support: 6.4,
    stability: 6.6,
    weightScore: 5.8,
    breathability: 5.8,
    outdoorDurability: 6.9,
    retroStyleScore: 8.4,
    footWidthFit: "regular",
    summary: "Everyday retro court shoe with easy styling.",
    imageUrl: ""
  }
];

function insertMissingShoes(db: Database.Database): void {
  const existingRows = db.prepare("SELECT name FROM shoes").all() as Array<{ name: string }>;
  const existingNames = new Set(existingRows.map((row) => row.name));
  const missing = seedShoes.filter((shoe) => !existingNames.has(shoe.name));

  if (missing.length === 0) return;

  const insert = db.prepare(`
    INSERT INTO shoes (
      name, brand, era, releaseYear, priceKRW, positionTag,
      traction, cushioning, support, stability, weightScore,
      breathability, outdoorDurability, retroStyleScore, footWidthFit,
      summary, imageUrl
    ) VALUES (
      @name, @brand, @era, @releaseYear, @priceKRW, @positionTag,
      @traction, @cushioning, @support, @stability, @weightScore,
      @breathability, @outdoorDurability, @retroStyleScore, @footWidthFit,
      @summary, @imageUrl
    )
  `);

  const transaction = db.transaction((items: SeedShoe[]) => {
    for (const item of items) {
      insert.run(item);
    }
  });

  transaction(missing);
}

export function seedDatabaseIfEmpty(db: Database.Database): void {
  insertMissingShoes(db);
}

export function reseedDatabase(db: Database.Database): void {
  db.exec("DELETE FROM favorites;");
  db.exec("DELETE FROM recommendation_logs;");
  db.exec("DELETE FROM shoes;");
  insertMissingShoes(db);
}
